pipeline {
	agent any
	stages{
		stage('Compile stage'){
			steps{
				withMaven(maven:'Maven_3_2_3'){
					sh 'mvn clean compile'
				}
			}
		}
		stage('Test stage'){
			steps{
				withMaven(maven:'Maven_3_2_3'){
					sh 'mvn test'
				}
			}
		}
		stage('Deploy stage'){
			steps{
				withMaven(maven:'Maven_3_2_3'){
					sh 'mvn deploy'
				}
			}
		}
		
	}

}